### ISSUE TITLE
TypeError: feathers.errors is not a function

### ISSUE THREAD

**Issue by funkybunky** [feathersjs/feathers-logger#4]
Following the steps under https://github.com/feathersjs/feathers-logger#vanilla-usage, I get that TypeError at the line:
`.configure(feathers.errors())`

**Comment by ekryski** [comment]
Sorry @funkybunky this is massively out of date. Right now you probably shouldn't use feathers-logger with new versions of feathers-errors. Really you should just use your own logging function like [the one created by the generator](https://github.com/feathersjs/generator-feathers/blob/master/generators/app/templates/static/src/middleware/logger.js). Any Express compatible one will work.

I'll add a disclaimer to the readme and look to update it over the next week or two.

**Comment by daffl** [comment]
This was just a documentation issue. The logger should still work with latest Feathers as described.
